trigger:
  - master

pool:
  name: Local-Machine-Agents

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildPushDeploy
    displayName: Build Docker images and deploy to Kubernetes
    workspace:
      clean: all
    steps:
      - checkout: self

      - script: |
          echo "Building backend Docker image..."
          docker build -f rja-backend/Dockerfile -t joke-backend:latest ./rja-backend
        displayName: Build Backend Docker Image
        workingDirectory: 'random-joke-azure'

      - script: |
          echo "Building frontend Docker image..."
          docker build -f rja-frontend/Dockerfile -t joke-frontend:latest ./rja-frontend
        displayName: Build Frontend Docker Image
        workingDirectory: 'random-joke-azure'

      - script: |
          echo "Deploying backend to Kubernetes..."
          kubectl apply -f ./k8s/backend-deployment.yaml
          kubectl apply -f ./k8s/backend-service.yaml
        displayName: Deploy Backend
        workingDirectory: 'random-joke-azure'

      - script: |
          echo "Deploying frontend to Kubernetes..."
          kubectl apply -f ./k8s/frontend-deployment.yaml
          kubectl apply -f ./k8s/frontend-service.yaml
        displayName: Deploy Frontend
        workingDirectory: 'random-joke-azure'