trigger:
  - master

pool:
  name: Local-Machine-Agents  # Local agent pool

steps:
  - checkout: self
  
stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildPushDeploy
    displayName: Build Docker images and deploy to Kubernetes
    steps:

    - script: |
        echo "Building backend Docker image..."
        docker build -t joke-backend:latest ./rja-backend
      displayName: Build Backend Docker Image

    - script: |
        echo "Building frontend Docker image..."
        docker build -t joke-frontend:latest ./rja-frontend
      displayName: Build Frontend Docker Image

    - script: |
        echo "Deploying backend to Kubernetes..."
        kubectl apply -f ./k8s/backend-deployment.yaml
        kubectl apply -f ./k8s/backend-service.yaml
      displayName: Deploy Backend

    - script: |
        echo "Deploying frontend to Kubernetes..."
        kubectl apply -f ./k8s/frontend-deployment.yaml
        kubectl apply -f ./k8s/frontend-service.yaml
      displayName: Deploy Frontend

