trigger:
  - master

pool:
  name: Local-Machine-Agents

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildPushDeploy
    displayName: Build Docker images and deploy to Kubernetes
    steps:
      - checkout: self

      # Build backend
      - script: |
          echo "Building backend Docker image..."
          cd rja-backend
          docker build -t joke-backend:latest .
        displayName: Build Backend Docker Image

      # Build frontend
      - script: |
          echo "Building frontend Docker image..."
          cd rja-frontend
          docker build -t joke-frontend:latest .
        displayName: Build Frontend Docker Image

      # Deploy backend
      - script: |
          echo "Deploying backend to Kubernetes..."
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
        displayName: Deploy Backend

      # Deploy frontend
      - script: |
          echo "Deploying frontend to Kubernetes..."
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
        displayName: Deploy Frontend