trigger:
  - master

pool:
  name: Local-Machine-Agents  # Local agent pool

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildPushDeploy
    displayName: Build Docker images and deploy to Kubernetes
    steps:
      - checkout: self

      - script: |
          echo "Building backend Docker image..."
          cd random-joke-azure
          docker build -f rja-backend/Dockerfile -t joke-backend:latest ./rja-backend
        displayName: Build Backend Docker Image

      - script: |
          echo "Building frontend Docker image..."
          cd random-joke-azure
          docker build -f rja-frontend/Dockerfile -t joke-frontend:latest ./rja-frontend
        displayName: Build Frontend Docker Image

      - script: |
          echo "Deploying backend to Kubernetes..."
          cd random-joke-azure
          kubectl apply -f ./k8s/backend-deployment.yaml
          kubectl apply -f ./k8s/backend-service.yaml
        displayName: Deploy Backend

      - script: |
          echo "Deploying frontend to Kubernetes..."
          cd random-joke-azure
          kubectl apply -f ./k8s/frontend-deployment.yaml
          kubectl apply -f ./k8s/frontend-service.yaml
        displayName: Deploy Frontend