trigger:
  - master

pool:
  name: Local-Machine-Agents

stages:
- stage: BuildAndDeploy
  jobs:
  - job: Build
    steps:
      - checkout: self  # Simple checkout now
      
      - script: |
          echo "Building Backend..."
          docker build -t joke-backend -f rja-backend/Dockerfile rja-backend
        displayName: Build Backend

      - script: |
          echo "Building Frontend..."
          docker build -t joke-frontend -f rja-frontend/Dockerfile rja-frontend
        displayName: Build Frontend

  - job: Deploy
    dependsOn: Build
    steps:
      - checkout: self
      
      - script: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
        displayName: Deploy to Kubernetes