apiVersion: apps/v1
kind: Deployment
metadata:
   name : joke-backend
spec:
   replicas: 1
   selector:
      matchLabels:
          app: joke-backend
   template:
      metadata:
        labels:
           app: joke-backend
      spec:
         containers:
            - name: backend
              image: gajapathi22/joke-backend:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 3001