apiVersion: apps/v1
kind: Deployment
metadata:
   name : joke-frontend
spec:
   replicas: 1
   selector:
      matchLabels:
          app: joke-frontend
   template:
      metadata:
        labels:
           app: joke-frontend
      spec:
         containers:
            - name: frontend
              image: gajapathi22/joke-frontend:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 80